/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_magandorid_JniCallNative */

#ifndef _Included_com_example_magandorid_JniCallNative
#define _Included_com_example_magandorid_JniCallNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_magandorid_JniCallNative
 * Method:    solve_mag
 * Signature: ([D[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_example_magandorid_JniCallNative_solve_1mag
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
